CREATE USER marlito WITH PASSWORD 'marlon3113';

GRANT ALL PRIVILEGES ON DATABASE deliveryeats TO marlito;

\connect deliveryeats;

GRANT ALL ON SCHEMA public TO marlito;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO marlito;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON SEQUENCES TO marlito;